### PR TITLE
HTML Nexus response handling fixed

### PR DESCRIPTION
**Pull request by aresok**
See https://github.com/ThoughtWorksInc/go-maven-poller/issues/7 - this request provides fix for the issue.
Additionally, it reduces the size of created artifact (Jar) from ~9 to ~2MB.

### CODE REVIEW

**Comment by aresok** [comment]
Hi,
any progress with this one?
We are using the plugin in some our internal pipelines, and it works (GO_PACKAGE__LOCATION env variable is fine).

**Comment by arvindsv** [comment]
Hi @aresok. I'm closing this PR. I've removed all the files in this repo, and I've put in a [redirection message](https://github.com/ThoughtWorksInc/go-maven-poller) to your repo. I've submitted a PR for the [plugins page on go.cd](https://github.com/gocd/gocd.github.io/pull/101), which changes the owner to you. That should get accepted soon.

You might want to look at the [issues]() on this go-maven-poller project, and open corresponding issues, if they make sense. You can link them back to the issues on this repo. It is not going to get deleted (at least by me).

Let me know if I've missed anything.

Cheers,
Aravind

**Comment by arvindsv** [comment]
The PR has been accepted by @mdaliejaz. You're the owner now! Congratulations! Feel free to ask for help, any time.

**Comment by jefftrimm** [comment]
The new github site doesn't seem to have any ability to submit issues?  https://github.com/aresok/go-maven-poller https://github.com/aresok/go-maven-poller

Also, it doesn't look like the latest release includes all of the latest fixes?  https://github.com/aresok/go-maven-poller/releases https://github.com/aresok/go-maven-poller/releases

-Jeff

**Comment by arvindsv** [comment]
I checked with one of my forks, and issues can be enabled in the settings of the repository. @aresok needs to do that. @aresok?

**Comment by aresok** [comment]
Hi,
currently I'm involved in other things - I will look at the poller in about
a week; sorry for that, regards!

**Comment by aresok** [comment]
Hi,
I published a release - available here:
https://github.com/aresok/go-maven-poller/releases/tag/v0.3.2
I also make it able to add issues.

Is there something else required to make the release 'complete'?

## regards,

Arek Sokołowski

**Comment by arvindsv** [comment]
Hey @aresok,

I think that's all there is to it. I'm thinking of turning off issues in the original repo, but I don't know who has access to that. I'll leave it for now, and if people start opening issues there, then I'll find out the owner and ask them to turn off issues.

If you need to migrate (create duplicate) issues in your repo, please do that. If the issues at https://github.com/ThoughtWorksInc/go-maven-poller/issues are no longer relevant, I can close them and point them to your repo. Would you like me to do that?

Congratulations on the first release!

Cheers,
Aravind

**Pull request closed without merging**
